const CustomUserModel = require("../models/CustomUserModel.js");
const TaskModel = require("../models/TaskModel.js");

// Render Pages
exports.signup = async (req, res) => {    
  res.render('customUser/signup');    
};

exports.login = async (req, res) => {    
  res.render('customUser/login');    
};


exports.task = async (req, res) => {

  const userCookie = req.cookies.user;

  if (!userCookie) {
    return res.render("customUser/task", { 
      userData: null
    });
  }

  let parsedUser;

  try {
    parsedUser = typeof userCookie === "string"
      ? JSON.parse(userCookie)
      : userCookie;
  } catch (error) {
    console.log("Invalid JSON in cookie:", userCookie);

    // fallback (error হলেও crash করবে না)
    parsedUser = {};
  }

  const taskData = await TaskModel.find({});
  
  res.render("customUser/task", { 
    userData: true,
    taskData,
    email: parsedUser.email || null
  });

};





exports.leaderboard = async (req, res) => {
  try {
    // সব user নিয়ে আসা
    const allUsers = await CustomUserModel.find({});

    // যদি data না থাকে
    if (!allUsers) {
      return res.render("customUser/leaderboard", { allUsers: [] });
    }

    // data পাঠানো
    res.render("customUser/leaderboard", { allUsers });

  } catch (err) {
    console.error(err);
    res.render("customUser/leaderboard", { allUsers: [] });
  }
};

exports.dashboard = async (req, res) => {
  try {
    const userCookie = req.cookies.user;

    if (!userCookie) {
      return res.render("customUser/dashboard", { 
        userData: null, 
        referredUsers: [],
        allUsers: []
      });
    }

    const parsedUser = typeof userCookie === "string"
      ? JSON.parse(userCookie)
      : userCookie;

    const userData = await CustomUserModel.findOne({
      email: parsedUser.email
    });

    if (!userData) {
      return res.render("customUser/dashboard", { 
        userData: null, 
        referredUsers: [],
        allUsers: []
      });
    }

    // referred users
    let referredUsers = [];
    if (userData.refers && userData.refers.length > 0) {
      referredUsers = await CustomUserModel.find({
        email: { $in: userData.refers }
      });
    }

    // ✅ সব user (no sort)
    const allUsers = await CustomUserModel.find({});

    res.render("customUser/dashboard", { 
      userData, 
      referredUsers,
      allUsers
    });

  } catch (err) {
    console.error(err);
    res.render("customUser/dashboard", { 
      userData: null, 
      referredUsers: [],
      allUsers: []
    });
  }
};

// POST /signup
exports.signupPost = async (req, res) => {
  try {
    const { fullName, username, email, number, age, password, referCode } = req.body;
    const profilePic = req.file ? `/uploads/${req.file.filename}` : null;

    if (!profilePic) return res.send("Profile picture is required.");

    // check existing user
    const existingUser = await CustomUserModel.findOne({ $or: [{ email }, { username }] });
    if (existingUser) {
      return res.send("User with same email or username already exists.");
    }

    // create new user
    const newUser = await CustomUserModel.create({
      profilePic,
      fullName,
      username,
      email,
      number,
      age,
      password
      // referCode auto-generated by schema if not provided
    });

    // যদি form থেকে referCode আসে
    if (referCode) {
      // ডাটাবেসে দেখুন referCode আছে কি না
      const referredUser = await CustomUserModel.findOne({ referCode: referCode });

      if (referredUser) {
        // থাকলে তার refers অ্যারেতে নতুন ইউজারের email push করুন
        referredUser.refers.push(email);

        // coin আপডেট করুন (+5)
        referredUser.coin = (parseInt(referredUser.coin) || 0) + 5;

        await referredUser.save();
      }
      // না থাকলে কিছু হবেনা
    }

    // save user in cookies
    res.cookie("user", {
      id: newUser._id,
      username: newUser.username,
      email: newUser.email,
      profilePic: newUser.profilePic
    }, { httpOnly: true });

    res.redirect("/user/dashboard");

  } catch (err) {
    console.error(err);
    res.send("Something went wrong.");
  }
};

// POST /login
exports.loginPost = async (req, res) => {
  try {
    const { loginId, password } = req.body;
    const login = loginId.toLowerCase(); // lowercase for username/email

    // find by email, username, or number + include password
    const user = await CustomUserModel.findOne({
      $or: [
        { email: login },
        { username: login },
        { number: loginId }
      ]
    }).select("+password"); // ⚠ password include

    if (!user) {
      if (login.includes("@")) return res.status(400).json({ success: false, message: "Incorrect Email" });
      else if (/^\d+$/.test(loginId)) return res.status(400).json({ success: false, message: "Incorrect Number" });
      else return res.status(400).json({ success: false, message: "Incorrect Username" });
    }

    if (user.password !== password) {
      return res.status(400).json({ success: false, message: "Incorrect Password" });
    }

    // ✅ Status check
    if (!user.status) {
      const statusMsg = user.statusMessage; // use correct field
      return res.status(403).json({ success: false, message: statusMsg });
    }

    // login successful → cookies save
    res.cookie("user", {
      id: user._id,
      username: user.username,
      email: user.email,
      profilePic: user.profilePic
    }, { httpOnly: true });

    return res.json({ success: true, redirect: "/user/dashboard" });

  } catch (err) {
    console.error(err);
    return res.status(500).json({ success: false, message: "Something went wrong." });
  }
};

// GET /logout
exports.logout = (req, res) => {
  res.clearCookie("user");
  res.redirect("/user/login");
};
